// 內容載入器
// 實現真正的 lazy loading，只在需要時載入對應的內容文件

// 快取已載入的內容模組
const loadedModules = new Map();

// ID 到文件路徑的映射表
const contentFileMap = {
  // 文法
  'grammar-particles-wa': '../data/content/grammar-particles-wa.js',
  'grammar-particles-ga': '../data/content/grammar-particles-ga.js',
  'grammar-particles-wo': '../data/content/grammar-particles-wo.js',
  'grammar-desu-masu': '../data/content/grammar-desu-masu.js',
  'grammar-kana-basics': '../data/content/grammar-kana-basics.js',
  'grammar-yoon': '../data/content/grammar-yoon.js',
  'grammar-keigo-overview': '../data/content/grammar-keigo-overview.js',
  'grammar-adverbs': '../data/content/grammar-adverbs.js',
  'grammar-aux-verbs': '../data/content/grammar-aux-verbs.js',
  'grammar-parts-of-speech': '../data/content/grammar-parts-of-speech.js',
  'grammar-adjectives-i': '../data/content/grammar-adjectives-i.js',
  'grammar-adjectives-na': '../data/content/grammar-adjectives-na.js',
  'grammar-particles-ni': '../data/content/grammar-particles-ni.js',
  'grammar-particles-de': '../data/content/grammar-particles-de.js',
  'grammar-particles-he': '../data/content/grammar-particles-he.js',
  'grammar-particles-kara': '../data/content/grammar-particles-kara.js',
  'grammar-particles-made': '../data/content/grammar-particles-made.js',
  'grammar-particles-to': '../data/content/grammar-particles-to.js',
  'grammar-particles-ya': '../data/content/grammar-particles-ya.js',
  'grammar-particles-mo': '../data/content/grammar-particles-mo.js',
  'grammar-verb-te-form': '../data/content/grammar-verb-te-form.js',
  'grammar-verb-ta-form': '../data/content/grammar-verb-ta-form.js',
  'grammar-verb-nai-form': '../data/content/grammar-verb-nai-form.js',
  'grammar-pattern-tai': '../data/content/grammar-pattern-tai.js',
  'grammar-pattern-nakereba-naranai': '../data/content/grammar-pattern-nakereba-naranai.js',
  'grammar-pattern-temo-ii': '../data/content/grammar-pattern-temo-ii.js',
  'grammar-particles-yori': '../data/content/grammar-particles-yori.js',
  'grammar-particles-hodo': '../data/content/grammar-particles-hodo.js',
  'grammar-particles-nado': '../data/content/grammar-particles-nado.js',
  'grammar-verb-potential': '../data/content/grammar-verb-potential.js',
  'grammar-pattern-te-shimau': '../data/content/grammar-pattern-te-shimau.js',
  'grammar-pattern-te-miru': '../data/content/grammar-pattern-te-miru.js',
  'grammar-verb-causative': '../data/content/grammar-verb-causative.js',
  'grammar-verb-passive': '../data/content/grammar-verb-passive.js',
  'grammar-pattern-nagara': '../data/content/grammar-pattern-nagara.js',
  'grammar-pattern-noni': '../data/content/grammar-pattern-noni.js',
  'grammar-particles-dake': '../data/content/grammar-particles-dake.js',
  'grammar-particles-shika': '../data/content/grammar-particles-shika.js',
  'grammar-pattern-ba': '../data/content/grammar-pattern-ba.js',
  'grammar-pattern-tara': '../data/content/grammar-pattern-tara.js',
  'grammar-verb-causative-passive': '../data/content/grammar-verb-causative-passive.js',
  'grammar-pattern-te-oku': '../data/content/grammar-pattern-te-oku.js',
  'grammar-pattern-te-iku': '../data/content/grammar-pattern-te-iku.js',
  'grammar-pattern-te-kuru': '../data/content/grammar-pattern-te-kuru.js',
  'grammar-pattern-te-ageru': '../data/content/grammar-pattern-te-ageru.js',
  'grammar-pattern-te-morau': '../data/content/grammar-pattern-te-morau.js',
  'grammar-pattern-te-kureru': '../data/content/grammar-pattern-te-kureru.js',
  'grammar-pattern-rashii': '../data/content/grammar-pattern-rashii.js',
  'grammar-pattern-you-da': '../data/content/grammar-pattern-you-da.js',
  'grammar-pattern-mitai-da': '../data/content/grammar-pattern-mitai-da.js',
  'grammar-pattern-sou-da-appearance': '../data/content/grammar-pattern-sou-da-appearance.js',
  'grammar-pattern-sou-da-hearsay': '../data/content/grammar-pattern-sou-da-hearsay.js',
  'grammar-pattern-bakari': '../data/content/grammar-pattern-bakari.js',
  'grammar-pattern-tokoro': '../data/content/grammar-pattern-tokoro.js',
  'grammar-pattern-no-da': '../data/content/grammar-pattern-no-da.js',
  'grammar-pattern-no-ni': '../data/content/grammar-pattern-no-ni.js',
  'grammar-pattern-te-hoshii': '../data/content/grammar-pattern-te-hoshii.js',
  'grammar-pattern-to-omou': '../data/content/grammar-pattern-to-omou.js',
  'grammar-pattern-kara-reason': '../data/content/grammar-pattern-kara-reason.js',
  'grammar-pattern-node': '../data/content/grammar-pattern-node.js',
  'grammar-pattern-tame-ni': '../data/content/grammar-pattern-tame-ni.js',
  'grammar-pattern-you-ni': '../data/content/grammar-pattern-you-ni.js',
  'grammar-pattern-koto-ga-dekiru': '../data/content/grammar-pattern-koto-ga-dekiru.js',
  'grammar-pattern-koto-ga-aru': '../data/content/grammar-pattern-koto-ga-aru.js',
  'grammar-pattern-te-wa-ikenai': '../data/content/grammar-pattern-te-wa-ikenai.js',
  'grammar-pattern-nakute-wa-ikenai': '../data/content/grammar-pattern-nakute-wa-ikenai.js',
  'grammar-pattern-beki-da': '../data/content/grammar-pattern-beki-da.js',
  'grammar-pattern-nai-de': '../data/content/grammar-pattern-nai-de.js',
  'grammar-pattern-to-shite': '../data/content/grammar-pattern-to-shite.js',
  'grammar-pattern-ni-tsuite': '../data/content/grammar-pattern-ni-tsuite.js',
  'grammar-pattern-ni-totte': '../data/content/grammar-pattern-ni-totte.js',
  'grammar-pattern-ni-taishite': '../data/content/grammar-pattern-ni-taishite.js',
  'grammar-pattern-ni-shitagatte': '../data/content/grammar-pattern-ni-shitagatte.js',
  'grammar-pattern-ni-tsuite-wa': '../data/content/grammar-pattern-ni-tsuite-wa.js',
  'grammar-particles-bakari': '../data/content/grammar-particles-bakari.js',
  'grammar-pattern-koto-ni-naru': '../data/content/grammar-pattern-koto-ni-naru.js',
  'grammar-pattern-koto-ni-suru': '../data/content/grammar-pattern-koto-ni-suru.js',
  'grammar-keigo-teineigo': '../data/content/grammar-keigo-teineigo.js',
  'grammar-keigo-sonkeigo': '../data/content/grammar-keigo-sonkeigo.js',
  'grammar-keigo-kenjogo': '../data/content/grammar-keigo-kenjogo.js',
  'grammar-pattern-wake-da': '../data/content/grammar-pattern-wake-da.js',
  'grammar-pattern-hazu-da': '../data/content/grammar-pattern-hazu-da.js',
  'grammar-particles-sae': '../data/content/grammar-particles-sae.js',
  'grammar-particles-demo': '../data/content/grammar-particles-demo.js',
  'grammar-pattern-mono-da': '../data/content/grammar-pattern-mono-da.js',
  'grammar-pattern-koto-da': '../data/content/grammar-pattern-koto-da.js',
  'grammar-particles-koso': '../data/content/grammar-particles-koso.js',
  'grammar-particles-sura': '../data/content/grammar-particles-sura.js',
  'grammar-pattern-bakari-ka': '../data/content/grammar-pattern-bakari-ka.js',
  'grammar-pattern-dokoro-ka': '../data/content/grammar-pattern-dokoro-ka.js',
  'grammar-pattern-ni-kagirazu': '../data/content/grammar-pattern-ni-kagirazu.js',
  'grammar-pattern-ni-shite-mo': '../data/content/grammar-pattern-ni-shite-mo.js',
  'grammar-pattern-ni-seyo': '../data/content/grammar-pattern-ni-seyo.js',
  'grammar-pattern-to-iu-wake': '../data/content/grammar-pattern-to-iu-wake.js',
  'grammar-pattern-mono-no': '../data/content/grammar-pattern-mono-no.js',
  'grammar-pattern-to-ie': '../data/content/grammar-pattern-to-ie.js',
  'grammar-pattern-ni-shiro': '../data/content/grammar-pattern-ni-shiro.js',
  'grammar-pattern-to-wa': '../data/content/grammar-pattern-to-wa.js',
  'grammar-pattern-to-iu-mono': '../data/content/grammar-pattern-to-iu-mono.js',
  'grammar-pattern-to-iu-koto': '../data/content/grammar-pattern-to-iu-koto.js',
  'grammar-pattern-to-iu-koto-ni': '../data/content/grammar-pattern-to-iu-koto-ni.js',
  'grammar-pattern-to-iu-koto-wa': '../data/content/grammar-pattern-to-iu-koto-wa.js',
  'grammar-pattern-to-iu-koto-mo-nai': '../data/content/grammar-pattern-to-iu-koto-mo-nai.js',
  'grammar-pattern-to-iu-koto-de-mo-nai': '../data/content/grammar-pattern-to-iu-koto-de-mo-nai.js',
  'grammar-pattern-to-iu-koto-wa-nai': '../data/content/grammar-pattern-to-iu-koto-wa-nai.js',
  'grammar-pattern-to-iu-koto-de-wa-nai': '../data/content/grammar-pattern-to-iu-koto-de-wa-nai.js',
  'grammar-pattern-to-iu-koto-ni-wa-nai': '../data/content/grammar-pattern-to-iu-koto-ni-wa-nai.js',
  'grammar-pattern-to-iu-koto-de-wa-naku': '../data/content/grammar-pattern-to-iu-koto-de-wa-naku.js',
  'grammar-pattern-to-iu-koto-ni-wa-aru': '../data/content/grammar-pattern-to-iu-koto-ni-wa-aru.js',
  'grammar-pattern-to-iu-koto-de-wa-naku-te': '../data/content/grammar-pattern-to-iu-koto-de-wa-naku-te.js',
  'grammar-pattern-to-iu-koto-ni-wa-naranai': '../data/content/grammar-pattern-to-iu-koto-ni-wa-naranai.js',
  'grammar-pattern-to-iu-koto-ni-wa-naranai-kara': '../data/content/grammar-pattern-to-iu-koto-ni-wa-naranai-kara.js',
  'grammar-pattern-to-iu-koto-ni-wa-naranai-node': '../data/content/grammar-pattern-to-iu-koto-ni-wa-naranai-node.js',
  'grammar-pattern-to-iu-koto-ni-wa-naranai-kedo': '../data/content/grammar-pattern-to-iu-koto-ni-wa-naranai-kedo.js',
  'grammar-pattern-to-iu-koto-ni-wa-naranai-ga': '../data/content/grammar-pattern-to-iu-koto-ni-wa-naranai-ga.js',
  'grammar-pattern-to-iu-koto-ni-wa-naranai-shikashi': '../data/content/grammar-pattern-to-iu-koto-ni-wa-naranai-shikashi.js',
  'grammar-pattern-to-iu-koto-ni-wa-naranai-tadashi': '../data/content/grammar-pattern-to-iu-koto-ni-wa-naranai-tadashi.js',
  'grammar-pattern-to-iu-koto-ni-wa-naranai-tomo': '../data/content/grammar-pattern-to-iu-koto-ni-wa-naranai-tomo.js',
  'grammar-pattern-to-iu-koto-ni-wa-naranai-tadashi-ga': '../data/content/grammar-pattern-to-iu-koto-ni-wa-naranai-tadashi-ga.js',
  // 五十音
  'kana-hiragana': '../data/content/kana-hiragana.js',
  'kana-katakana': '../data/content/kana-katakana.js',
  'kana-yoon': '../data/content/kana-yoon.js',
  'kana-choon': '../data/content/kana-choon.js',
  'kana-sokuon': '../data/content/kana-sokuon.js',
  'kana-seion': '../data/content/kana-seion.js',
  'kana-hatsuon': '../data/content/kana-hatsuon.js',
  'kana-dakuon-handakuon': '../data/content/kana-dakuon-handakuon.js',
  // 單字
  'category-colors': '../data/content/category-colors.js',
  'category-body-parts': '../data/content/vocabulary-body-parts.js',
  'category-family': '../data/content/vocabulary-family.js',
  'category-food': '../data/content/vocabulary-food.js',
  'category-animals': '../data/content/vocabulary-animals.js',
  'category-weather': '../data/content/vocabulary-weather.js',
  'category-time': '../data/content/vocabulary-time.js',
  'category-seasons': '../data/content/category-seasons.js',
  'category-months': '../data/content/category-months.js',
  'category-weekdays': '../data/content/category-weekdays.js',
  'category-counting': '../data/content/category-counting.js',
  'category-greetings': '../data/content/category-greetings.js',
  'category-polite-expressions': '../data/content/category-polite-expressions.js',
  'category-directions': '../data/content/category-directions.js',
  'category-weather-conditions': '../data/content/category-weather-conditions.js',
  'category-daily-conversation': '../data/content/category-daily-conversation.js',
  'category-restaurant': '../data/content/category-restaurant.js',
  'category-shopping-phrases': '../data/content/category-shopping-phrases.js',
  'category-transportation-phrases': '../data/content/category-transportation-phrases.js',
  'category-hospital': '../data/content/category-hospital.js',
  'category-phone': '../data/content/category-phone.js',
  'category-email': '../data/content/category-email.js',
  'category-travel': '../data/content/category-travel.js',
  'category-hotel': '../data/content/category-hotel.js',
  'category-bank': '../data/content/category-bank.js',
  'category-post-office': '../data/content/category-post-office.js',
  'category-office': '../data/content/category-office.js',
  'category-school-phrases': '../data/content/category-school-phrases.js',
  'category-direction': '../data/content/vocabulary-direction.js',
  'category-transportation': '../data/content/vocabulary-transportation.js',
  'category-occupation': '../data/content/vocabulary-occupation.js',
  'category-school': '../data/content/vocabulary-school.js',
  'category-shopping': '../data/content/vocabulary-shopping.js',
  'category-sports': '../data/content/vocabulary-sports.js',
  'category-emotions': '../data/content/vocabulary-emotions.js',
  'category-health': '../data/content/vocabulary-health.js',
  'category-entertainment': '../data/content/vocabulary-entertainment.js',
  'category-music': '../data/content/vocabulary-music.js',
  'category-nature': '../data/content/vocabulary-nature.js',
  'category-clothing': '../data/content/vocabulary-clothing.js',
  'category-building': '../data/content/vocabulary-building.js',
  'category-numbers': '../data/content/vocabulary-numbers.js',
  'category-technology': '../data/content/vocabulary-technology.js',
  'category-hobbies': '../data/content/vocabulary-hobbies.js',
  'category-weather-extended': '../data/content/vocabulary-weather-extended.js',
  'category-appearance': '../data/content/vocabulary-appearance.js',
  'category-personality': '../data/content/vocabulary-personality.js',
  'category-feelings-extended': '../data/content/vocabulary-feelings-extended.js',
  'category-actions': '../data/content/vocabulary-actions.js',
  'category-daily-activities': '../data/content/vocabulary-daily-activities.js',
  'category-places': '../data/content/vocabulary-places.js',
  'category-verbs-basic': '../data/content/vocabulary-verbs-basic.js',
  'category-adjectives-basic': '../data/content/vocabulary-adjectives-basic.js',
  'category-questions': '../data/content/vocabulary-questions.js',
  'category-conjunctions': '../data/content/vocabulary-conjunctions.js',
  'category-prepositions': '../data/content/vocabulary-prepositions.js',
  'category-adverbs-time': '../data/content/vocabulary-adverbs-time.js',
  'category-adverbs-degree': '../data/content/vocabulary-adverbs-degree.js',
  'category-adverbs-manner': '../data/content/vocabulary-adverbs-manner.js',
  'vocabulary-gairaigo': '../data/content/vocabulary-gairaigo.js',
  'vocabulary-wago': '../data/content/vocabulary-wago.js',
  'vocabulary-kango': '../data/content/vocabulary-kango.js',
  'vocabulary-gakusei': '../data/content/vocabulary-gakusei.js',
  'vocabulary-sensei': '../data/content/vocabulary-sensei.js',
  'vocabulary-tomodachi': '../data/content/vocabulary-tomodachi.js',
  'vocabulary-hon': '../data/content/vocabulary-hon.js',
  'vocabulary-kuruma': '../data/content/vocabulary-kuruma.js',
  'vocabulary-tabemono': '../data/content/vocabulary-tabemono.js',
  'vocabulary-yomu': '../data/content/vocabulary-yomu.js',
  'vocabulary-taberu': '../data/content/vocabulary-taberu.js',
  'vocabulary-iku': '../data/content/vocabulary-iku.js',
  'vocabulary-kuru': '../data/content/vocabulary-kuru.js',
  'vocabulary-suru': '../data/content/vocabulary-suru.js',
  'vocabulary-aruku': '../data/content/vocabulary-aruku.js',
  'vocabulary-miru': '../data/content/vocabulary-miru.js',
  'vocabulary-kiku': '../data/content/vocabulary-kiku.js',
  'vocabulary-hanasu': '../data/content/vocabulary-hanasu.js',
  'vocabulary-kau': '../data/content/vocabulary-kau.js',
  'vocabulary-uru': '../data/content/vocabulary-uru.js',
  'vocabulary-takai': '../data/content/vocabulary-takai.js',
  'vocabulary-atarashii': '../data/content/vocabulary-atarashii.js',
  'vocabulary-kirei': '../data/content/vocabulary-kirei.js',
  'vocabulary-shizuka': '../data/content/vocabulary-shizuka.js',
  'vocabulary-genki': '../data/content/vocabulary-genki.js',
  'vocabulary-ie': '../data/content/vocabulary-ie.js',
  'vocabulary-gakkou': '../data/content/vocabulary-gakkou.js',
  'vocabulary-toshokan': '../data/content/vocabulary-toshokan.js',
  'vocabulary-kouen': '../data/content/vocabulary-kouen.js',
  'vocabulary-eki': '../data/content/vocabulary-eki.js',
  'vocabulary-ichi': '../data/content/vocabulary-ichi.js',
  'vocabulary-ni': '../data/content/vocabulary-ni.js',
  'vocabulary-san': '../data/content/vocabulary-san.js',
  'vocabulary-yon': '../data/content/vocabulary-yon.js',
  'vocabulary-go': '../data/content/vocabulary-go.js',
  'vocabulary-kyou': '../data/content/vocabulary-kyou.js',
  'vocabulary-kinou': '../data/content/vocabulary-kinou.js',
  'vocabulary-ashita': '../data/content/vocabulary-ashita.js',
  'vocabulary-ima': '../data/content/vocabulary-ima.js',
  'vocabulary-nanji': '../data/content/vocabulary-nanji.js',
  'vocabulary-nani': '../data/content/vocabulary-nani.js',
  'vocabulary-doko': '../data/content/vocabulary-doko.js',
  'vocabulary-dare': '../data/content/vocabulary-dare.js',
  'vocabulary-kaku': '../data/content/vocabulary-kaku.js',
  'vocabulary-nomu': '../data/content/vocabulary-nomu.js',
  'vocabulary-kaeru': '../data/content/vocabulary-kaeru.js',
  'vocabulary-okiru': '../data/content/vocabulary-okiru.js',
  'vocabulary-neru': '../data/content/vocabulary-neru.js',
  'vocabulary-iru': '../data/content/vocabulary-iru.js',
  'vocabulary-aru': '../data/content/vocabulary-aru.js',
  'vocabulary-animal': '../data/content/vocabulary-animal.js',
  'vocabulary-akai': '../data/content/vocabulary-akai.js',
  'vocabulary-aoi': '../data/content/vocabulary-aoi.js',
  'vocabulary-shiroi': '../data/content/vocabulary-shiroi.js',
  'vocabulary-kuroi': '../data/content/vocabulary-kuroi.js',
  'vocabulary-kiiroi': '../data/content/vocabulary-kiiroi.js',
  'vocabulary-ookii': '../data/content/vocabulary-ookii.js',
  'vocabulary-chiisai': '../data/content/vocabulary-chiisai.js',
  'vocabulary-furui': '../data/content/vocabulary-furui.js',
  'vocabulary-oishii': '../data/content/vocabulary-oishii.js',
  'vocabulary-benri': '../data/content/vocabulary-benri.js',
  'vocabulary-suki': '../data/content/vocabulary-suki.js',
  'vocabulary-heya': '../data/content/vocabulary-heya.js',
  'vocabulary-mise': '../data/content/vocabulary-mise.js',
  'vocabulary-watashi': '../data/content/vocabulary-watashi.js',
  'vocabulary-anata': '../data/content/vocabulary-anata.js',
  'vocabulary-kore': '../data/content/vocabulary-kore.js',
  'vocabulary-sore': '../data/content/vocabulary-sore.js',
  'vocabulary-are': '../data/content/vocabulary-are.js',
  'vocabulary-tsukuru': '../data/content/vocabulary-tsukuru.js',
  'vocabulary-dekiru': '../data/content/vocabulary-dekiru.js',
  'vocabulary-omoshiroi': '../data/content/vocabulary-omoshiroi.js',
  'vocabulary-isogashii': '../data/content/vocabulary-isogashii.js',
  'vocabulary-yasui': '../data/content/vocabulary-yasui.js',
  'vocabulary-kawaru': '../data/content/vocabulary-kawaru.js',
  'vocabulary-kaeru-change': '../data/content/vocabulary-kaeru-change.js',
  'vocabulary-omou': '../data/content/vocabulary-omou.js',
  'vocabulary-kangaeru': '../data/content/vocabulary-kangaeru.js',
  'vocabulary-shiru': '../data/content/vocabulary-shiru.js',
  'vocabulary-wakaru': '../data/content/vocabulary-wakaru.js',
  'vocabulary-tsumori': '../data/content/vocabulary-tsumori.js',
  'vocabulary-hajimeru': '../data/content/vocabulary-hajimeru.js',
  'vocabulary-owaru': '../data/content/vocabulary-owaru.js',
  'vocabulary-tsuzukeru': '../data/content/vocabulary-tsuzukeru.js',
  'vocabulary-yameru': '../data/content/vocabulary-yameru.js',
  'vocabulary-sagasu': '../data/content/vocabulary-sagasu.js',
  'vocabulary-kakeru': '../data/content/vocabulary-kakeru.js',
  'vocabulary-okuru': '../data/content/vocabulary-okuru.js',
  'vocabulary-ukeru': '../data/content/vocabulary-ukeru.js',
  'vocabulary-tsutomeru': '../data/content/vocabulary-tsutomeru.js',
  'vocabulary-hayai': '../data/content/vocabulary-hayai.js',
  'vocabulary-osoi': '../data/content/vocabulary-osoi.js',
  'vocabulary-ageru': '../data/content/vocabulary-ageru.js',
  'vocabulary-morau': '../data/content/vocabulary-morau.js',
  'vocabulary-kureru': '../data/content/vocabulary-kureru.js',
  'vocabulary-ii': '../data/content/vocabulary-ii.js',
  'vocabulary-warui': '../data/content/vocabulary-warui.js',
  'vocabulary-samui': '../data/content/vocabulary-samui.js',
  'vocabulary-atsui': '../data/content/vocabulary-atsui.js',
  'vocabulary-tsumetai': '../data/content/vocabulary-tsumetai.js',
  'vocabulary-nemui': '../data/content/vocabulary-nemui.js',
  'vocabulary-tanoshii': '../data/content/vocabulary-tanoshii.js',
  'vocabulary-ureshii': '../data/content/vocabulary-ureshii.js',
  'vocabulary-kanashii': '../data/content/vocabulary-kanashii.js',
  'vocabulary-omoi': '../data/content/vocabulary-omoi.js',
  'vocabulary-karui': '../data/content/vocabulary-karui.js',
  'vocabulary-nagai': '../data/content/vocabulary-nagai.js',
  'vocabulary-mijikai': '../data/content/vocabulary-mijikai.js',
  'vocabulary-hiroi': '../data/content/vocabulary-hiroi.js',
  'vocabulary-semai': '../data/content/vocabulary-semai.js',
  'vocabulary-hikui': '../data/content/vocabulary-hikui.js',
  'vocabulary-mizu': '../data/content/vocabulary-mizu.js',
  'vocabulary-pan': '../data/content/vocabulary-pan.js',
  'vocabulary-ringo': '../data/content/vocabulary-ringo.js',
  'vocabulary-neko': '../data/content/vocabulary-neko.js',
  'vocabulary-inu': '../data/content/vocabulary-inu.js',
  'vocabulary-kawaii': '../data/content/vocabulary-kawaii.js',
  'vocabulary-tsukue': '../data/content/vocabulary-tsukue.js',
  'vocabulary-isu': '../data/content/vocabulary-isu.js',
  // 漢字
  'kanji-gaku': '../data/content/kanji-gaku.js',
  'kanji-sei': '../data/content/kanji-sei.js',
  'kanji-hon': '../data/content/kanji-hon.js',
  'kanji-ichi': '../data/content/kanji-ichi.js',
  'kanji-ni': '../data/content/kanji-ni.js',
  'kanji-san': '../data/content/kanji-san.js',
  'kanji-yon': '../data/content/kanji-yon.js',
  'kanji-go': '../data/content/kanji-go.js',
  'kanji-roku': '../data/content/kanji-roku.js',
  'kanji-nana': '../data/content/kanji-nana.js',
  'kanji-hachi': '../data/content/kanji-hachi.js',
  'kanji-kyuu': '../data/content/kanji-kyuu.js',
  'kanji-juu': '../data/content/kanji-juu.js',
  'kanji-hi': '../data/content/kanji-hi.js',
  'kanji-hito': '../data/content/kanji-hito.js',
  'kanji-kuchi': '../data/content/kanji-kuchi.js',
  'kanji-me': '../data/content/kanji-me.js',
  'kanji-tsuki': '../data/content/kanji-tsuki.js',
  'kanji-nen': '../data/content/kanji-nen.js',
  'kanji-toki': '../data/content/kanji-toki.js',
  'kanji-ka-fire': '../data/content/kanji-ka-fire.js',
  'kanji-mizu': '../data/content/kanji-mizu.js',
  'kanji-ki': '../data/content/kanji-ki.js',
  'kanji-kin': '../data/content/kanji-kin.js',
  'kanji-do': '../data/content/kanji-do.js',
  'kanji-ookii': '../data/content/kanji-ookii.js',
  'kanji-chiisai': '../data/content/kanji-chiisai.js',
  'kanji-ue': '../data/content/kanji-ue.js',
  'kanji-shita': '../data/content/kanji-shita.js',
  'kanji-naka': '../data/content/kanji-naka.js',
  'kanji-mae': '../data/content/kanji-mae.js',
  'kanji-ato': '../data/content/kanji-ato.js',
  'kanji-hidari': '../data/content/kanji-hidari.js',
  'kanji-migi': '../data/content/kanji-migi.js',
  'kanji-higashi': '../data/content/kanji-higashi.js',
  'kanji-nishi': '../data/content/kanji-nishi.js',
  'kanji-minami': '../data/content/kanji-minami.js',
  'kanji-kita': '../data/content/kanji-kita.js',
  'kanji-atarashii': '../data/content/kanji-atarashii.js',
  'kanji-furui': '../data/content/kanji-furui.js',
  'kanji-nagai': '../data/content/kanji-nagai.js',
  'kanji-mijikai': '../data/content/kanji-mijikai.js',
  'kanji-takai': '../data/content/kanji-takai.js',
  'kanji-hikui': '../data/content/kanji-hikui.js',
  'kanji-ooi': '../data/content/kanji-ooi.js',
  'kanji-sukunai': '../data/content/kanji-sukunai.js',
  'kanji-hayai': '../data/content/kanji-hayai.js',
  'kanji-osoi': '../data/content/kanji-osoi.js',
  'kanji-ii': '../data/content/kanji-ii.js',
  'kanji-warui': '../data/content/kanji-warui.js',
  'kanji-tsuyoi': '../data/content/kanji-tsuyoi.js',
  'kanji-yowai': '../data/content/kanji-yowai.js',
  'kanji-shiroi': '../data/content/kanji-shiroi.js',
  'kanji-kuroi': '../data/content/kanji-kuroi.js',
  'kanji-akai': '../data/content/kanji-akai.js',
  'kanji-aoi': '../data/content/kanji-aoi.js',
  'kanji-kiiroi': '../data/content/kanji-kiiroi.js',
  'kanji-midori': '../data/content/kanji-midori.js',
  'kanji-chairoi': '../data/content/kanji-chairoi.js',
  'kanji-te': '../data/content/kanji-te.js',
  'kanji-ashi': '../data/content/kanji-ashi.js',
  'kanji-mimi': '../data/content/kanji-mimi.js',
  'kanji-hana': '../data/content/kanji-hana.js',
  'kanji-atama': '../data/content/kanji-atama.js',
  'kanji-kubi': '../data/content/kanji-kubi.js',
  'kanji-kokoro': '../data/content/kanji-kokoro.js',
  'kanji-karada': '../data/content/kanji-karada.js',
  'kanji-hana-flower': '../data/content/kanji-hana-flower.js',
  'kanji-yama': '../data/content/kanji-yama.js',
  'kanji-kawa': '../data/content/kanji-kawa.js',
  'kanji-sora': '../data/content/kanji-sora.js',
  'kanji-umi': '../data/content/kanji-umi.js',
  'kanji-hoshi': '../data/content/kanji-hoshi.js',
  'kanji-kumo': '../data/content/kanji-kumo.js',
  'kanji-kuruma': '../data/content/kanji-kuruma.js',
  'kanji-den': '../data/content/kanji-den.js',
  'kanji-hanashi': '../data/content/kanji-hanashi.js',
  'kanji-mon': '../data/content/kanji-mon.js',
  'kanji-ie': '../data/content/kanji-ie.js',
  'kanji-mise': '../data/content/kanji-mise.js',
  'kanji-michi': '../data/content/kanji-michi.js',
  'kanji-sakana': '../data/content/kanji-sakana.js',
  'kanji-tori': '../data/content/kanji-tori.js',
  'kanji-inu': '../data/content/kanji-inu.js',
  'kanji-neko': '../data/content/kanji-neko.js',
  'kanji-kusa': '../data/content/kanji-kusa.js',
  'kanji-mori': '../data/content/kanji-mori.js',
  'kanji-hayashi': '../data/content/kanji-hayashi.js',
  'kanji-kaze': '../data/content/kanji-kaze.js',
  'kanji-ame': '../data/content/kanji-ame.js',
  'kanji-yuki': '../data/content/kanji-yuki.js',
  'kanji-koori': '../data/content/kanji-koori.js',
  'kanji-ishi': '../data/content/kanji-ishi.js',
  'kanji-tsuchi': '../data/content/kanji-tsuchi.js',
  'kanji-chi': '../data/content/kanji-chi.js',
  'kanji-ta': '../data/content/kanji-ta.js'
};

// ID 到導出變數名的映射表（特殊情況）
const idToExportNameMap = {
  // 主題單字：id 是 category-xxx，但 export 名稱是 vocabularyXxx
  'category-colors': 'vocabularyColors',
  'category-body-parts': 'vocabularyBodyParts',
  'category-family': 'vocabularyFamily',
  'category-food': 'vocabularyFood',
  'category-animals': 'vocabularyAnimals',
  'category-weather': 'vocabularyWeather',
  'category-time': 'vocabularyTime',
  'category-seasons': 'vocabularySeasons',
  'category-months': 'vocabularyMonths',
  'category-weekdays': 'vocabularyWeekdays',
  'category-counting': 'vocabularyCounting',
  'category-greetings': 'vocabularyGreetings',
  'category-polite-expressions': 'vocabularyPoliteExpressions',
  'category-directions': 'vocabularyDirections',
  'category-weather-conditions': 'vocabularyWeatherConditions',
  'category-daily-conversation': 'vocabularyDailyConversation',
  'category-restaurant': 'vocabularyRestaurant',
  'category-shopping-phrases': 'vocabularyShoppingPhrases',
  'category-transportation-phrases': 'vocabularyTransportationPhrases',
  'category-hospital': 'vocabularyHospital',
  'category-phone': 'vocabularyPhone',
  'category-email': 'vocabularyEmail',
  'category-travel': 'vocabularyTravel',
  'category-hotel': 'vocabularyHotel',
  'category-bank': 'vocabularyBank',
  'category-post-office': 'vocabularyPostOffice',
  'category-office': 'vocabularyOffice',
  'category-school-phrases': 'vocabularySchoolPhrases',
  'category-direction': 'vocabularyDirection',
  'category-transportation': 'vocabularyTransportation',
  'category-occupation': 'vocabularyOccupation',
  'category-school': 'vocabularySchool',
  'category-shopping': 'vocabularyShopping',
  'category-sports': 'vocabularySports',
  'category-emotions': 'vocabularyEmotions',
  'category-health': 'vocabularyHealth',
  'category-entertainment': 'vocabularyEntertainment',
  'category-music': 'vocabularyMusic',
  'category-nature': 'vocabularyNature',
  'category-clothing': 'vocabularyClothing',
  'category-building': 'vocabularyBuilding',
  'category-numbers': 'vocabularyNumbers',
  'category-technology': 'vocabularyTechnology',
  'category-hobbies': 'vocabularyHobbies',
  'category-weather-extended': 'vocabularyWeatherExtended',
  'category-appearance': 'vocabularyAppearance',
  'category-personality': 'vocabularyPersonality',
  'category-feelings-extended': 'vocabularyFeelingsExtended',
  'category-actions': 'vocabularyActions',
  'category-daily-activities': 'vocabularyDailyActivities',
  'category-places': 'vocabularyPlaces',
  'category-verbs-basic': 'vocabularyVerbsBasic',
  'category-adjectives-basic': 'vocabularyAdjectivesBasic',
  'category-questions': 'vocabularyQuestions',
  'category-conjunctions': 'vocabularyConjunctions',
  'category-prepositions': 'vocabularyPrepositions',
  'category-adverbs-time': 'vocabularyAdverbsTime',
  'category-adverbs-degree': 'vocabularyAdverbsDegree',
  'category-adverbs-manner': 'vocabularyAdverbsManner',
};

// ID 到導出變數名的映射表（將 kebab-case 轉換為 camelCase）
function idToExportName(id) {
  // 先檢查是否有特殊映射
  if (idToExportNameMap[id]) {
    return idToExportNameMap[id];
  }
  // 將 kebab-case 轉換為 camelCase
  return id.replace(/-([a-z])/g, (g) => g[1].toUpperCase());
}

/**
 * 載入內容
 * @param {string} id - 內容 ID
 * @returns {Promise<Object|null>} 內容物件或 null
 */
export async function loadContent(id) {
  if (!id) return null;

  const filePath = contentFileMap[id];
  if (!filePath) {
    console.warn(`[content-loader] Content "${id}" not found in contentFileMap`);
    return null;
  }

  // 如果已經載入過這個模組，直接從快取返回對應的內容
  if (loadedModules.has(filePath)) {
    const module = loadedModules.get(filePath);
    const exportName = idToExportName(id);
    return module[exportName] || null;
  }

  try {
    // 動態載入模組
    const module = await import(filePath);
    loadedModules.set(filePath, module);

    // 從模組中提取對應的內容
    const exportName = idToExportName(id);
    return module[exportName] || null;
  } catch (error) {
    console.error(`[content-loader] Failed to load content file: ${filePath}`, error);
    return null;
  }
}

/**
 * 取得內容類別
 * @param {string} id - 內容 ID
 * @returns {Promise<string|null>} 內容類別或 null
 */
export async function getContentCategory(id) {
  const content = await loadContent(id);
  return content ? content.category.type : null;
}

/**
 * 預載入多個內容（可選）
 * @param {string[]} ids - 內容 ID 陣列
 */
export async function preloadContent(ids) {
  const promises = ids.map(id => loadContent(id));
  await Promise.all(promises);
}

/**
 * 清除快取（用於開發時的熱重載）
 */
export function clearCache() {
  loadedModules.clear();
}
