// 匯出功能
import { t } from './i18n.js';

export function exportToMarkdown(retro, items) {
  let markdown = `# ${retro.title || t('retrospective.title')}\n\n`;
  
  if (retro.description) {
    markdown += `${retro.description}\n\n`;
  }
  
  markdown += `**${t('history.date')}**: ${retro.date}\n\n`;
  markdown += `---\n\n`;
  
  // How do you feel
  if (items.howDoYouFeel && items.howDoYouFeel.length > 0) {
    markdown += `## ${t('retrospective.howDoYouFeel')}\n\n`;
    items.howDoYouFeel.forEach((item, index) => {
      const author = item.author?.isAnonymous 
        ? t('retrospective.anonymous') 
        : (item.author?.name || 'Unknown');
      markdown += `${index + 1}. ${item.text} - *${author}* (${item.votes || 0} ${t('retrospective.votes')})\n`;
    });
    markdown += `\n`;
  }
  
  // What went well
  if (items.whatWentWell && items.whatWentWell.length > 0) {
    markdown += `## ${t('retrospective.whatWentWell')}\n\n`;
    items.whatWentWell.forEach((item, index) => {
      const author = item.author?.isAnonymous 
        ? t('retrospective.anonymous') 
        : (item.author?.name || 'Unknown');
      markdown += `${index + 1}. ${item.text} - *${author}* (${item.votes || 0} ${t('retrospective.votes')})\n`;
    });
    markdown += `\n`;
  }
  
  // What didn't go well
  if (items.whatDidntGoWell && items.whatDidntGoWell.length > 0) {
    markdown += `## ${t('retrospective.whatDidntGoWell')}\n\n`;
    items.whatDidntGoWell.forEach((item, index) => {
      const author = item.author?.isAnonymous 
        ? t('retrospective.anonymous') 
        : (item.author?.name || 'Unknown');
      markdown += `${index + 1}. ${item.text} - *${author}* (${item.votes || 0} ${t('retrospective.votes')})\n`;
    });
    markdown += `\n`;
  }
  
  // What needs to change
  if (items.whatNeedsChange && items.whatNeedsChange.length > 0) {
    markdown += `## ${t('retrospective.whatNeedsChange')}\n\n`;
    items.whatNeedsChange.forEach((item, index) => {
      const author = item.author?.isAnonymous 
        ? t('retrospective.anonymous') 
        : (item.author?.name || 'Unknown');
      markdown += `${index + 1}. ${item.text} - *${author}* (${item.votes || 0} ${t('retrospective.votes')})\n`;
    });
    markdown += `\n`;
  }
  
  // Shout outs
  if (items.shoutOuts && items.shoutOuts.length > 0) {
    markdown += `## ${t('retrospective.shoutOuts')}\n\n`;
    items.shoutOuts.forEach((item, index) => {
      const author = item.author?.isAnonymous 
        ? t('retrospective.anonymous') 
        : (item.author?.name || 'Unknown');
      markdown += `${index + 1}. ${item.text} - *${author}* (${item.votes || 0} ${t('retrospective.votes')})\n`;
    });
    markdown += `\n`;
  }
  
  markdown += `---\n\n`;
  markdown += `*Generated by Retro - ${new Date().toLocaleString()}*\n`;
  
  return markdown;
}

